//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicsHub_FrontEnd.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        int RegisterUser(string userFirstName, string userLastName, string userEmail, string userPhone, string userPassword, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        System.Threading.Tasks.Task<int> RegisterUserAsync(string userFirstName, string userLastName, string userEmail, string userPhone, string userPassword, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        System.Tuple<int, string> LoginUser(string userEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        System.Threading.Tasks.Task<System.Tuple<int, string>> LoginUserAsync(string userEmail, string userPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ElectronicsHub_FrontEnd.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ElectronicsHub_FrontEnd.ServiceReference1.IService1>, ElectronicsHub_FrontEnd.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegisterUser(string userFirstName, string userLastName, string userEmail, string userPhone, string userPassword, string userType) {
            return base.Channel.RegisterUser(userFirstName, userLastName, userEmail, userPhone, userPassword, userType);
        }
        
        public System.Threading.Tasks.Task<int> RegisterUserAsync(string userFirstName, string userLastName, string userEmail, string userPhone, string userPassword, string userType) {
            return base.Channel.RegisterUserAsync(userFirstName, userLastName, userEmail, userPhone, userPassword, userType);
        }
        
        public System.Tuple<int, string> LoginUser(string userEmail, string userPassword) {
            return base.Channel.LoginUser(userEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<int, string>> LoginUserAsync(string userEmail, string userPassword) {
            return base.Channel.LoginUserAsync(userEmail, userPassword);
        }
    }
}
