//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicsHub_FrontEnd.ElectronicsHubBackendService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ElectronicsHub_Backend")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Cart[] CartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReviewUpvote[] ProductReviewUpvotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReview[] ProductReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Cart[] Carts {
            get {
                return this.CartsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartsField, value) != true)) {
                    this.CartsField = value;
                    this.RaisePropertyChanged("Carts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReviewUpvote[] ProductReviewUpvotes {
            get {
                return this.ProductReviewUpvotesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductReviewUpvotesField, value) != true)) {
                    this.ProductReviewUpvotesField = value;
                    this.RaisePropertyChanged("ProductReviewUpvotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReview[] ProductReviews {
            get {
                return this.ProductReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductReviewsField, value) != true)) {
                    this.ProductReviewsField = value;
                    this.RaisePropertyChanged("ProductReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate {
            get {
                return this.RegistrationDateField;
            }
            set {
                if ((this.RegistrationDateField.Equals(value) != true)) {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/ElectronicsHub_Backend")]
    [System.SerializableAttribute()]
    public partial class Cart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.CartItem[] CartItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartId {
            get {
                return this.CartIdField;
            }
            set {
                if ((this.CartIdField.Equals(value) != true)) {
                    this.CartIdField = value;
                    this.RaisePropertyChanged("CartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.CartItem[] CartItems {
            get {
                return this.CartItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartItemsField, value) != true)) {
                    this.CartItemsField = value;
                    this.RaisePropertyChanged("CartItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductReviewUpvote", Namespace="http://schemas.datacontract.org/2004/07/ElectronicsHub_Backend")]
    [System.SerializableAttribute()]
    public partial class ProductReviewUpvote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReview ProductReviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductReviewIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductReviewUpvoteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UpvoterUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReview ProductReview {
            get {
                return this.ProductReviewField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductReviewField, value) != true)) {
                    this.ProductReviewField = value;
                    this.RaisePropertyChanged("ProductReview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductReviewId {
            get {
                return this.ProductReviewIdField;
            }
            set {
                if ((this.ProductReviewIdField.Equals(value) != true)) {
                    this.ProductReviewIdField = value;
                    this.RaisePropertyChanged("ProductReviewId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductReviewUpvoteId {
            get {
                return this.ProductReviewUpvoteIdField;
            }
            set {
                if ((this.ProductReviewUpvoteIdField.Equals(value) != true)) {
                    this.ProductReviewUpvoteIdField = value;
                    this.RaisePropertyChanged("ProductReviewUpvoteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UpvoterUserId {
            get {
                return this.UpvoterUserIdField;
            }
            set {
                if ((this.UpvoterUserIdField.Equals(value) != true)) {
                    this.UpvoterUserIdField = value;
                    this.RaisePropertyChanged("UpvoterUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductReview", Namespace="http://schemas.datacontract.org/2004/07/ElectronicsHub_Backend")]
    [System.SerializableAttribute()]
    public partial class ProductReview : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductReviewIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReviewUpvote[] ProductReviewUpvotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReviewDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductReviewId {
            get {
                return this.ProductReviewIdField;
            }
            set {
                if ((this.ProductReviewIdField.Equals(value) != true)) {
                    this.ProductReviewIdField = value;
                    this.RaisePropertyChanged("ProductReviewId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReviewUpvote[] ProductReviewUpvotes {
            get {
                return this.ProductReviewUpvotesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductReviewUpvotesField, value) != true)) {
                    this.ProductReviewUpvotesField = value;
                    this.RaisePropertyChanged("ProductReviewUpvotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReviewDate {
            get {
                return this.ReviewDateField;
            }
            set {
                if ((this.ReviewDateField.Equals(value) != true)) {
                    this.ReviewDateField = value;
                    this.RaisePropertyChanged("ReviewDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReviewerName {
            get {
                return this.ReviewerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewerNameField, value) != true)) {
                    this.ReviewerNameField = value;
                    this.RaisePropertyChanged("ReviewerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItem", Namespace="http://schemas.datacontract.org/2004/07/ElectronicsHub_Backend")]
    [System.SerializableAttribute()]
    public partial class CartItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Cart CartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Cart Cart {
            get {
                return this.CartField;
            }
            set {
                if ((object.ReferenceEquals(this.CartField, value) != true)) {
                    this.CartField = value;
                    this.RaisePropertyChanged("Cart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartId {
            get {
                return this.CartIdField;
            }
            set {
                if ((this.CartIdField.Equals(value) != true)) {
                    this.CartIdField = value;
                    this.RaisePropertyChanged("CartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemId {
            get {
                return this.CartItemIdField;
            }
            set {
                if ((this.CartItemIdField.Equals(value) != true)) {
                    this.CartItemIdField = value;
                    this.RaisePropertyChanged("CartItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/ElectronicsHub_Backend")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.CartItem[] CartItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory ProductCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImageExtra[] ProductImageExtrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImage[] ProductImagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReview[] ProductReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductSubcategory ProductSubcategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductSubcategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.CartItem[] CartItems {
            get {
                return this.CartItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartItemsField, value) != true)) {
                    this.CartItemsField = value;
                    this.RaisePropertyChanged("CartItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory ProductCategory {
            get {
                return this.ProductCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryField, value) != true)) {
                    this.ProductCategoryField = value;
                    this.RaisePropertyChanged("ProductCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryId {
            get {
                return this.ProductCategoryIdField;
            }
            set {
                if ((this.ProductCategoryIdField.Equals(value) != true)) {
                    this.ProductCategoryIdField = value;
                    this.RaisePropertyChanged("ProductCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImageExtra[] ProductImageExtras {
            get {
                return this.ProductImageExtrasField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageExtrasField, value) != true)) {
                    this.ProductImageExtrasField = value;
                    this.RaisePropertyChanged("ProductImageExtras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImage[] ProductImages {
            get {
                return this.ProductImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImagesField, value) != true)) {
                    this.ProductImagesField = value;
                    this.RaisePropertyChanged("ProductImages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReview[] ProductReviews {
            get {
                return this.ProductReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductReviewsField, value) != true)) {
                    this.ProductReviewsField = value;
                    this.RaisePropertyChanged("ProductReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductSubcategory ProductSubcategory {
            get {
                return this.ProductSubcategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSubcategoryField, value) != true)) {
                    this.ProductSubcategoryField = value;
                    this.RaisePropertyChanged("ProductSubcategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductSubcategoryId {
            get {
                return this.ProductSubcategoryIdField;
            }
            set {
                if ((this.ProductSubcategoryIdField.Equals(value) != true)) {
                    this.ProductSubcategoryIdField = value;
                    this.RaisePropertyChanged("ProductSubcategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCategory", Namespace="http://schemas.datacontract.org/2004/07/ElectronicsHub_Backend")]
    [System.SerializableAttribute()]
    public partial class ProductCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductSubcategory[] ProductSubcategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryId {
            get {
                return this.ProductCategoryIdField;
            }
            set {
                if ((this.ProductCategoryIdField.Equals(value) != true)) {
                    this.ProductCategoryIdField = value;
                    this.RaisePropertyChanged("ProductCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductSubcategory[] ProductSubcategories {
            get {
                return this.ProductSubcategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSubcategoriesField, value) != true)) {
                    this.ProductSubcategoriesField = value;
                    this.RaisePropertyChanged("ProductSubcategories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSubcategory", Namespace="http://schemas.datacontract.org/2004/07/ElectronicsHub_Backend")]
    [System.SerializableAttribute()]
    public partial class ProductSubcategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory ProductCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductSubcategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory ProductCategory {
            get {
                return this.ProductCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryField, value) != true)) {
                    this.ProductCategoryField = value;
                    this.RaisePropertyChanged("ProductCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryId {
            get {
                return this.ProductCategoryIdField;
            }
            set {
                if ((this.ProductCategoryIdField.Equals(value) != true)) {
                    this.ProductCategoryIdField = value;
                    this.RaisePropertyChanged("ProductCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductSubcategoryId {
            get {
                return this.ProductSubcategoryIdField;
            }
            set {
                if ((this.ProductSubcategoryIdField.Equals(value) != true)) {
                    this.ProductSubcategoryIdField = value;
                    this.RaisePropertyChanged("ProductSubcategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductImageExtra", Namespace="http://schemas.datacontract.org/2004/07/ElectronicsHub_Backend")]
    [System.SerializableAttribute()]
    public partial class ProductImageExtra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductImageExtraIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductImageExtraId {
            get {
                return this.ProductImageExtraIdField;
            }
            set {
                if ((this.ProductImageExtraIdField.Equals(value) != true)) {
                    this.ProductImageExtraIdField = value;
                    this.RaisePropertyChanged("ProductImageExtraId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductImage", Namespace="http://schemas.datacontract.org/2004/07/ElectronicsHub_Backend")]
    [System.SerializableAttribute()]
    public partial class ProductImage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LargePhotoUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LargePhotoUrl {
            get {
                return this.LargePhotoUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.LargePhotoUrlField, value) != true)) {
                    this.LargePhotoUrlField = value;
                    this.RaisePropertyChanged("LargePhotoUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductImageId {
            get {
                return this.ProductImageIdField;
            }
            set {
                if ((this.ProductImageIdField.Equals(value) != true)) {
                    this.ProductImageIdField = value;
                    this.RaisePropertyChanged("ProductImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbnailUrl {
            get {
                return this.ThumbnailUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailUrlField, value) != true)) {
                    this.ThumbnailUrlField = value;
                    this.RaisePropertyChanged("ThumbnailUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ElectronicsHubBackendService.IBackendService")]
    public interface IBackendService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/RegisterUser", ReplyAction="http://tempuri.org/IBackendService/RegisterUserResponse")]
        bool RegisterUser(string firstName, string lastName, string email, string phone, string password, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/RegisterUser", ReplyAction="http://tempuri.org/IBackendService/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(string firstName, string lastName, string email, string phone, string password, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/LoginUser", ReplyAction="http://tempuri.org/IBackendService/LoginUserResponse")]
        int LoginUser(string userEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/LoginUser", ReplyAction="http://tempuri.org/IBackendService/LoginUserResponse")]
        System.Threading.Tasks.Task<int> LoginUserAsync(string userEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetUser", ReplyAction="http://tempuri.org/IBackendService/GetUserResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.User GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetUser", ReplyAction="http://tempuri.org/IBackendService/GetUserResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.User> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductCategory", ReplyAction="http://tempuri.org/IBackendService/GetProductCategoryResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory GetProductCategory(int prodCatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductCategory", ReplyAction="http://tempuri.org/IBackendService/GetProductCategoryResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory> GetProductCategoryAsync(int prodCatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductCategories", ReplyAction="http://tempuri.org/IBackendService/GetProductCategoriesResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory[] GetProductCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductCategories", ReplyAction="http://tempuri.org/IBackendService/GetProductCategoriesResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory[]> GetProductCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductSubcategories", ReplyAction="http://tempuri.org/IBackendService/GetProductSubcategoriesResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductSubcategory[] GetProductSubcategories(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductSubcategories", ReplyAction="http://tempuri.org/IBackendService/GetProductSubcategoriesResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductSubcategory[]> GetProductSubcategoriesAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetAllProducts", ReplyAction="http://tempuri.org/IBackendService/GetAllProductsResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetAllProducts", ReplyAction="http://tempuri.org/IBackendService/GetAllProductsResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[]> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductById", ReplyAction="http://tempuri.org/IBackendService/GetProductByIdResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product GetProductById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductById", ReplyAction="http://tempuri.org/IBackendService/GetProductByIdResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product> GetProductByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductsByCategory", ReplyAction="http://tempuri.org/IBackendService/GetProductsByCategoryResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[] GetProductsByCategory(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductsByCategory", ReplyAction="http://tempuri.org/IBackendService/GetProductsByCategoryResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[]> GetProductsByCategoryAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductsBySubcategory", ReplyAction="http://tempuri.org/IBackendService/GetProductsBySubcategoryResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[] GetProductsBySubcategory(int subcategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductsBySubcategory", ReplyAction="http://tempuri.org/IBackendService/GetProductsBySubcategoryResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[]> GetProductsBySubcategoryAsync(int subcategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductReviews", ReplyAction="http://tempuri.org/IBackendService/GetProductReviewsResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReview[] GetProductReviews(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductReviews", ReplyAction="http://tempuri.org/IBackendService/GetProductReviewsResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReview[]> GetProductReviewsAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductImage", ReplyAction="http://tempuri.org/IBackendService/GetProductImageResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImage GetProductImage(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductImage", ReplyAction="http://tempuri.org/IBackendService/GetProductImageResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImage> GetProductImageAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetAdditionalProductImages", ReplyAction="http://tempuri.org/IBackendService/GetAdditionalProductImagesResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImageExtra[] GetAdditionalProductImages(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetAdditionalProductImages", ReplyAction="http://tempuri.org/IBackendService/GetAdditionalProductImagesResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImageExtra[]> GetAdditionalProductImagesAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/UpvoteProductReview", ReplyAction="http://tempuri.org/IBackendService/UpvoteProductReviewResponse")]
        bool UpvoteProductReview(int customerId, int reviewId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/UpvoteProductReview", ReplyAction="http://tempuri.org/IBackendService/UpvoteProductReviewResponse")]
        System.Threading.Tasks.Task<bool> UpvoteProductReviewAsync(int customerId, int reviewId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductReviewUpvoteCount", ReplyAction="http://tempuri.org/IBackendService/GetProductReviewUpvoteCountResponse")]
        int GetProductReviewUpvoteCount(int prodReviewId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetProductReviewUpvoteCount", ReplyAction="http://tempuri.org/IBackendService/GetProductReviewUpvoteCountResponse")]
        System.Threading.Tasks.Task<int> GetProductReviewUpvoteCountAsync(int prodReviewId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetCart", ReplyAction="http://tempuri.org/IBackendService/GetCartResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Cart GetCart(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetCart", ReplyAction="http://tempuri.org/IBackendService/GetCartResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Cart> GetCartAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetCartItems", ReplyAction="http://tempuri.org/IBackendService/GetCartItemsResponse")]
        ElectronicsHub_FrontEnd.ElectronicsHubBackendService.CartItem[] GetCartItems(int cardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendService/GetCartItems", ReplyAction="http://tempuri.org/IBackendService/GetCartItemsResponse")]
        System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.CartItem[]> GetCartItemsAsync(int cardId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBackendServiceChannel : ElectronicsHub_FrontEnd.ElectronicsHubBackendService.IBackendService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackendServiceClient : System.ServiceModel.ClientBase<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.IBackendService>, ElectronicsHub_FrontEnd.ElectronicsHubBackendService.IBackendService {
        
        public BackendServiceClient() {
        }
        
        public BackendServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackendServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackendServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackendServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterUser(string firstName, string lastName, string email, string phone, string password, string role) {
            return base.Channel.RegisterUser(firstName, lastName, email, phone, password, role);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(string firstName, string lastName, string email, string phone, string password, string role) {
            return base.Channel.RegisterUserAsync(firstName, lastName, email, phone, password, role);
        }
        
        public int LoginUser(string userEmail, string userPassword) {
            return base.Channel.LoginUser(userEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<int> LoginUserAsync(string userEmail, string userPassword) {
            return base.Channel.LoginUserAsync(userEmail, userPassword);
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.User GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.User> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory GetProductCategory(int prodCatId) {
            return base.Channel.GetProductCategory(prodCatId);
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory> GetProductCategoryAsync(int prodCatId) {
            return base.Channel.GetProductCategoryAsync(prodCatId);
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory[] GetProductCategories() {
            return base.Channel.GetProductCategories();
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductCategory[]> GetProductCategoriesAsync() {
            return base.Channel.GetProductCategoriesAsync();
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductSubcategory[] GetProductSubcategories(int categoryId) {
            return base.Channel.GetProductSubcategories(categoryId);
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductSubcategory[]> GetProductSubcategoriesAsync(int categoryId) {
            return base.Channel.GetProductSubcategoriesAsync(categoryId);
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[]> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product GetProductById(int id) {
            return base.Channel.GetProductById(id);
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product> GetProductByIdAsync(int id) {
            return base.Channel.GetProductByIdAsync(id);
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[] GetProductsByCategory(int categoryId) {
            return base.Channel.GetProductsByCategory(categoryId);
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[]> GetProductsByCategoryAsync(int categoryId) {
            return base.Channel.GetProductsByCategoryAsync(categoryId);
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[] GetProductsBySubcategory(int subcategoryId) {
            return base.Channel.GetProductsBySubcategory(subcategoryId);
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Product[]> GetProductsBySubcategoryAsync(int subcategoryId) {
            return base.Channel.GetProductsBySubcategoryAsync(subcategoryId);
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReview[] GetProductReviews(int productId) {
            return base.Channel.GetProductReviews(productId);
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductReview[]> GetProductReviewsAsync(int productId) {
            return base.Channel.GetProductReviewsAsync(productId);
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImage GetProductImage(int productId) {
            return base.Channel.GetProductImage(productId);
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImage> GetProductImageAsync(int productId) {
            return base.Channel.GetProductImageAsync(productId);
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImageExtra[] GetAdditionalProductImages(int productId) {
            return base.Channel.GetAdditionalProductImages(productId);
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.ProductImageExtra[]> GetAdditionalProductImagesAsync(int productId) {
            return base.Channel.GetAdditionalProductImagesAsync(productId);
        }
        
        public bool UpvoteProductReview(int customerId, int reviewId) {
            return base.Channel.UpvoteProductReview(customerId, reviewId);
        }
        
        public System.Threading.Tasks.Task<bool> UpvoteProductReviewAsync(int customerId, int reviewId) {
            return base.Channel.UpvoteProductReviewAsync(customerId, reviewId);
        }
        
        public int GetProductReviewUpvoteCount(int prodReviewId) {
            return base.Channel.GetProductReviewUpvoteCount(prodReviewId);
        }
        
        public System.Threading.Tasks.Task<int> GetProductReviewUpvoteCountAsync(int prodReviewId) {
            return base.Channel.GetProductReviewUpvoteCountAsync(prodReviewId);
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Cart GetCart(int customerId) {
            return base.Channel.GetCart(customerId);
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.Cart> GetCartAsync(int customerId) {
            return base.Channel.GetCartAsync(customerId);
        }
        
        public ElectronicsHub_FrontEnd.ElectronicsHubBackendService.CartItem[] GetCartItems(int cardId) {
            return base.Channel.GetCartItems(cardId);
        }
        
        public System.Threading.Tasks.Task<ElectronicsHub_FrontEnd.ElectronicsHubBackendService.CartItem[]> GetCartItemsAsync(int cardId) {
            return base.Channel.GetCartItemsAsync(cardId);
        }
    }
}
